components/xr/scene/assets-default.tsx
components/xr/scene/index.tsx
components/xr/scene/landing.tsx
components/xr/scene/scene-environment.tsx
components/xr/scene/scene-landing.tsx
config/default.json
pages/space.tsx

- A-Frame is throwing an error
- was working before trying to add routes

working on landing page

---

components/xr/video360/Video360Room.tsx
components/xr/video360/VideoControls.scss
components/xr/video360/VideoControls.tsx

We'll be refactoring this into an A-Frame component so I just made something that will work for now. The navigation won't work until we fix kxr-dev#25 Exiting the video gallery.
But this solves kxr-dev#23 Unclear how to exit video.

Back navigation for end of video

---

classes/aframe/camera/camera-rig.ts
classes/aframe/camera/fuse-cursor.ts
classes/aframe/camera/mouse-cursor.ts
components/xr/aframe/player.tsx
components/xr/player/player.tsx
components/xr/scene/scene-dream.tsx
components/xr/scene/scene-video-grid.tsx
components/xr/scene/scene.tsx

- uses fuse-cursor when on GearVR

added mouse input

---

components/ui/Login/style.scss
components/ui/NavUserWidget/index.tsx
components/ui/NavUserWidget/style.scss

https://github.com/xrchat/xrchat-client/issues/48

fix login button color to white

---

components/xr/aframe/media-cell.tsx
components/xr/scene/scene-explore.tsx

- also fixed video details description

media images are two sided

---

classes/aframe/layout/GridUtils.ts
components/xr/aframe/arrow.tsx
components/xr/aframe/grid.tsx
components/xr/scene/scene-explore.tsx

- dream now also has pagination

abstracted pagination into grid component

---

components/xr/aframe/index.tsx
components/xr/aframe/text-cell.tsx
components/xr/aframe/video-details.tsx
package.json

- text-cell component uses clipping planes to prevent text being
rendered outside cell height

fixed videoDetails overflow

---

components/ui/Auth/ConfirmEmail.tsx
redux/auth/service.ts

Corresponding with the PR https://github.com/xrchat/xrchat-server/pull/165

fix password login issue

---

components/ui/NavUserWidget/index.tsx
components/ui/Profile/profileDown.tsx

Made logout button actually logout the user instead of just closing the profile dropdown.

---

components/ui/Friends/MyFriends.tsx
components/ui/Friends/UserItem.tsx
components/ui/Friends/UserList.tsx
interfaces/Relationship.ts
interfaces/User.ts
package.json
redux/user/service.ts

https://github.com/xrchat/xrchat-client/issues/137

Friend search

---

components/ui/VideoSeeker/index.tsx
components/ui/VideoSeeker/style.scss
components/xr/video360/Video360Room.tsx
components/xr/video360/VideoControls.tsx

Solves issue #103
It seems there is only ever 1 buffered time range, but it should still work if there are multiple.

Video360 buffered

---

components/ui/NavUserWidget/index.tsx
components/ui/Profile/profileDown.tsx

- contacts linked to /friends/friends

Avatar for dropdown menu icon when logged in

---

components/ui/Admin/Console.tsx
components/ui/Admin/VideoModal.tsx
components/ui/Admin/admin.scss
components/ui/NavUserWidget/index.tsx
components/ui/Profile/profileDown.tsx
interfaces/StaticResource.ts
interfaces/User.ts
pages/admin.tsx
redux/actions.ts
redux/admin/actions.ts
redux/admin/reducers.ts
redux/admin/selector.ts
redux/admin/service.ts
redux/video/actions.ts
redux/video/service.ts

**What is the purpose of this PR?**
Updating the backend to work with the admin console on the client.
Preparing content to be gated behind one or more paid tiers.
Better implement staticResource patching so that changing the thumbnail_url on
a video will cache the new thumbnail and remove the old one.
**What does issue #s are solved by this PR?**
No specific issues
**What unit tests have been put in place?**
None
**What files or features are including in this PR that are not related to the main feature?**
Updated field 'staticResource.mime_type' to 'staticResource.mimeType'.
Added table subscriptionLevel and added it as a field to staticResource.
After learning more about how React works, better passed along needed props from NavUserWidget to ProfileDown.
**How does our QA team test this …

Added admin console at /admin that can create, edit, and delete videos.

---

components/ui/Invite/SeatItem.tsx
components/ui/Invite/SeatList.tsx
components/ui/Invite/style.scss
components/xr/aframe/arrow.tsx
components/xr/aframe/grid.tsx

Fixes the problems with the subscription seat management page.

Seat page fixes

---

components/xr/aframe/video-details.tsx
components/xr/scene/assets.tsx
components/xr/scene/dream.tsx
components/xr/scene/explore.tsx
components/xr/scene/landing.tsx
config/default.json

- fixed aspect ratio
- moved grid closer

grid parameters set from config

---

components/xr/scene/landing.tsx
config/default.json

- disables clicking the banners
- can still navigate to the url of a coming soon page

Added Coming Soon banners

---

components/ui/VideoSeeker/style.scss

#320 
CSS video seeker full width and at very bottom of screen.
Play pause button moved just above seeker bar in the bottom left corner, while the back button is located just above this button.

css video seeker at very bottom and full width.

---

components/xr/aframe/video-details.tsx
components/xr/scene/explore.tsx

fixes video details ui in explore

---

components/xr/video360/VideoControls.tsx

- set redux video360 playing state to false in
componentWillUnmount

fixed videos continuing to play after hitting browser back button

---

components/ui/Admin/Console.tsx
components/ui/Admin/admin.scss

Fixed admin page so that a long list of videos scrolls properly.

Admin scroll

---

classes/aframe/camera/camera-rig.ts
classes/aframe/camera/fuse-cursor.ts
classes/aframe/camera/mouse-cursor.ts
classes/aframe/controls/player-controls.ts
components/ui/VideoSeeker/index.tsx
components/xr/aframe/player.tsx
components/xr/scene/index.tsx
components/xr/scene/video.tsx
components/xr/video360/Video360Room.tsx

- uses Player for camera
- removes movement controls in video room

added fuse controls to video camera

---

classes/aframe/camera/fuse-cursor.ts
components/xr/aframe/highlight.tsx
components/xr/aframe/video-controls.tsx

- multiple highlight components can be added to an entity

highlight playpause and back buttons independently

---

components/xr/aframe/video-details.tsx
components/xr/video360/Video360Room.tsx

- added highlight to watch/back buttons

removed click to play text inVR

---

components/xr/aframe/media-cell.tsx
components/xr/aframe/video-details.tsx
components/xr/scene/explore.tsx
components/xr/scene/index.tsx

- also added stopPropagation to navigate event

made video format consistent with navigation

---

classes/aframe/camera/mouse-cursor.ts

see https://github.com/aframevr/aframe/issues/4141

sets fuseTimeout to zero to remove double clicks

---

.travis.yml
classes/aframe/camera/mouse-cursor.ts
components/ui/VideoSeeker/index.tsx
components/xr/aframe/media-cell.tsx
components/xr/aframe/video-controls.tsx
components/xr/aframe/video-details.tsx
components/xr/scene/assets.tsx
components/xr/scene/explore.tsx
components/xr/scene/index.tsx
components/xr/scene/landing.tsx
components/xr/scene/page-loader.tsx
components/xr/scene/videoGrid.tsx
components/xr/scene/vrRoom.tsx
components/xr/scene/vrRoomGrid.tsx
components/xr/video360/Video360Room.tsx
components/xr/video360/VideoControls.tsx
config/default.json
pages/[sceneName].tsx
redux/scenes/service.ts
scripts/deploy.sh
scripts/publish_dockerhub.sh
scripts/setup_helm.sh
utils/triggerNavigation.ts

Video player fixes.
Codebase sourcing more information from config.
Updated CI/CD process names to reflect rename to xr3ngine.

Master pull 6/1/20

---

components/xr/aframe/text-cell.tsx

- prevents the need to reload on update

cache fonts in text-cell

---

components/ui/VideoSeeker/index.tsx
components/ui/VideoSeeker/style.scss
components/xr/aframe/camera-angle.tsx
components/xr/aframe/fade.tsx
components/xr/aframe/index.tsx
components/xr/aframe/player.tsx
components/xr/aframe/template.tsx
components/xr/aframe/text-cell.tsx
components/xr/aframe/video-controls.tsx
components/xr/player/player.tsx
components/xr/scene/index.tsx
components/xr/scene/vrRoom.tsx
components/xr/video360/Video360Room.tsx
package.json
utils/secondsToString.ts

A number of visual fixes and improvements.

Master merge 6/2/20

---

classes/aframe/camera/camera-rig.ts
components/xr/aframe/player.tsx

- camera-rig accepts an array of cursor types

added touch controls to cardboard

---

components/xr/aframe/player.tsx

- removes look-controls when entering vr on mobile
- adds them back in when exiting

fixes rotation issue when exiting vr on mobile

---

components/xr/aframe/fuse-instructions.tsx
components/xr/aframe/index.tsx
components/xr/aframe/player.tsx

when first entering vr on mobile

displays instructions for fuse controls
